### ISSUE TITLE
Invitation to collaborate

### ISSUE THREAD

**Issue by marcandrews** [twitch-js/twitch.js#2]
I am leading an effort to continue supporting and developing `tmi.js` as [**`twitch-js`**](https://github.com/marcandrews/twitch-js). Several collaborators and I have already resolved many several issues and published them to [NPM](https://www.npmjs.com/package/twitch-js).

As evident by the many open PRs for `tmi.js`, there are many talented developers willing to contribute, so anyone who has a PR merged into `twitch-js` will obtain collaborator access and merge rights. Hopefully, this will help keep the project alive.

This project looks promising and I invite you to contribute to `twitch-js`. I am also asking if you would be willing to transfer the `twitch-js` GitHub organization to us so that the project can be better supported and maintained.

Looking forward to hearing from you.

Best regards,
Marc

**Comment by RosieCode95** [comment]
@marcandrews this repo will be focused towards the building of a new lib independent of the now tired TMI lib, i have no intention of using any of the TMI code in this repo.

thank you for the offer but i will have to decline as im now picking this up and will see it though alone if i have to.

your more than happy to colab if you so wish to (watch this space)

**Comment by RosieCode95** [comment]
PS: check [inDev branch](https://github.com/twitch-js/twitch.js/tree/indev) for incoming updates, 

i will close this issue for now, feel free to continue the discussion
